// flow-typed signature: 12554c3e97f94d7eb8b40cd670dbcf70
// flow-typed version: <<STUB>>/mongodb-autoincrement_v^1.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb-autoincrement'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb-autoincrement' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mongodb-autoincrement/index' {
  declare module.exports: $Exports<'mongodb-autoincrement'>;
}
declare module 'mongodb-autoincrement/index.js' {
  declare module.exports: $Exports<'mongodb-autoincrement'>;
}
